
plugins:
  - jekyll-default-layout
logo: "/assets/images/bear.png"

title: Xiong Siliang
description: Quantitative Engineer
theme: just-the-docs

url: https://github.com/Belightar/belightar.github.io

aux_links:
  Template Repository: https://github.com/Belightar/belightar.github.io

